### PR TITLE
Add support for Archivist

### PR DESCRIPTION
**Pull request by XertroV**

### CODE REVIEW

**Comment by nbeerten** [comment]
> The Archivist script name changes regularly to avoid caching, but this will reliably detect it.

Does Archivist only work for those already listed gamemodes? Or would it also trigger in COTD qualifications for example?

**Comment by XertroV** [comment]
Archivist *is* a game mode. It's called `TM_Archivist_<Nonce>_Local`. the Nonce part is replaced when the plugin loads. (If I didn't do this, then plugin updates would sometimes require a game restart)

No other game mode starts with `TM_Archivist_` so I use that as a test in my other plugins.

**Comment by nbeerten** [comment]
But archivist doesn't modify the current gamemode? So any `TM_Archivist_*` will always be time attack alike gamemode (so with LB on left)? (I literally have no idea how Archivist works nor have I used it yet, sorry for all the questions)

**Comment by XertroV** [comment]
It's TM_PlayMap_Local with some extra ghost stuff, basically. And yeah, it doesn't touch other game modes.

**Comment by nbeerten** [comment]
Ahh alright, was a little confused for a bit, will merge this now and do a release

**Pull request merged**
